### ISSUE TITLE
Extract tool generating invalid parameters file to deploy

### ISSUE THREAD

**Issue by rodrigoburim** [Azure/azure-api-management-devops-resource-kit#356] opened 2020-02-26 18:41 UTC
After extracting my APIM using the following parameters (**real values removed**):

```
{
  "sourceApimName": "removed",
  "destinationApimName": "removed",
  "resourceGroup": "removed",
  "fileFolder": "C:\\Source",
  "paramNamedValue": true,
  "paramApiLoggerId": true,
  "paramLogResourceId": true,
  "baseFileName": "removed"
}
```

I got this parameters.json file:

```
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "ApimServiceName": {
      "value": "removed"
    },
    "NamedValues": {
      "value": {
        "removed-prop-name": "removed-value"
      }
    },
    "ApiLoggerId": {
      "value": {
        "my-api-name": {
          "applicationinsights": "resource-address"
        }
      }
    },
    "LoggerResourceId": {
      "value": {
        "azuremonitor": null,
        "PROPNAME": "resource-address"
      }
    }
  },
  "resources": []
}
```

Later when running my release pipeline on Azure DevOps I've got this error:

**Deployment template validation failed: 'The template parameters 'ApiLoggerId, LoggerResourceId' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters for this template are 'ApimServiceName, NamedValues'. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'.**

Does anyone have any idea how to fix it? I've tried changing the schema to 2019-04-01, but got the same error.

**Comment by KevinHale-Bentley** [comment] 2020-03-04 21:54
What do the parameters sections of your template look like?  For example, here is one without the optional parameters:

 ```
 "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "ApimServiceName": {
      "type": "string"
    }
  }
```

Yours should have the parameter definitions for NamedValue, ApiLoggerId, and LoggerResourceId defined as well.

**Comment by rodrigoburim** [comment] 2020-03-26 18:39
I've discovered the issue, although my parameters.json file has 4 params, not all templates references those for 4 params.

So, if my template only references 2 parameters, using a parameters.json file with 4 parameters will rise an error.

**Comment by wvaneck** [comment] 2020-03-27 16:02
This is a general ARM issue, not specifically this toolkit. However, the issues is that the parameter file contains more parameters than the individual template needs. According to the ARM rules, this must be a one-to-one match. Very annoying... I am working on a temp solution but it should be resolved in ARM itself but since that may never happen, the Toolkit should ensure that every template it generates has the same parameters as defined in the parameters file.

**Comment by wvaneck** [comment] 2020-05-07 17:31
I have this issue resolved in Powershell as part of the [pipeline ](https://github.com/wvaneck/azure-api-management-devops-pipeline) sample I have created. 

In the Powershell script I have created for deployment, it uses the parameter template as a resource to retrieve the values from but the deployment is done using the -TemplateParameterObject option on the New-AzResourceGroupDeployment function. In my script I create a parameter object based on the defined parameters in the arm template with the values retrieved from the parameter file.

**Comment by AjaySewradj** [comment] 2020-12-11 11:36
Is it possible to have the Extractor tool generate a separate parameter file per template file?

so:
- apim-backends.template.json
- apim-backends.params.json
- apim-tags.template.json
- apim-tags.params.json
etc

**Comment by adrianhall** [comment] 2022-04-20 18:47
The extractor is meant to have a single master template with linked templates for ease of editing.  As such, it's only meant to be deployed as a single entity - not as a split entity.  However, I'll get the engineer to think about this.  It may be that we can't do anything and we simply close this as "by design".

**Comment by nmahajanoii** [comment] 2022-05-13 09:58
> Is it possible to have the Extractor tool generate a separate parameter file per template file?
> 
> so:
> 
> * apim-backends.template.json
> * apim-backends.params.json
> * apim-tags.template.json
> * apim-tags.params.json
>   etc
> 
> It would be very convenient for use in the yaml file:
> 
> ```yaml
> - task: AzureResourceGroupDeployment@2
>       displayName: 'Deploying API Backend'
>       inputs:
>         azureSubscription: $(azureSubscription)
>         location: $(location)
>         resourceGroupName: $(resourceGroupName)
>         csmFile: 'apim-backends.template.json'
>         csmParametersFile: 'apim-backends.params.json'
> ```

hey , are you able to deploy apis throgh yaml (Azure Devops / Github) to Azure APIM ? because I am struggling with template errors

**Comment by adrianhall** [comment] 2022-05-13 20:49
You have to copy the ARM templates and parameter files to an Azure Storage location and then use that.  This is normal for a pipeline deployment.

**Closed** 2022-08-04 14:07 UTC
Labels: bug, extractor

**Comment by f-alizada** [comment] 2022-08-04 14:16
Hello @rodrigoburim.
Please be informed that the ticket was closed, since the changes regarding this issue were merged into the main branch and will be available in future releases.
Changes include: 

- Generation of parameters file per each resource template 
- Possibility to redefine the output parameters directory name
- If previously the parameter directory were already existing, it will be saved with same name plus datetime of creation for future references and comparison (if applies)
