### ISSUE TITLE
Extrator : Error - Extracting products from service

### ISSUE THREAD

**Issue by jagadeeshRS** [Azure/azure-api-management-devops-resource-kit#226] opened 2019-09-02 10:49 UTC
Failed while Extracting products from service using extractor. 

Error occured: Sequence contains more than one matching element
Sequence contains more than one matching element

**Comment by miaojiang** [comment] 2019-09-04 00:39
@jagadeeshRS  I wasn't able to reproduce. Could you provide more details?

**Comment by bremnes** [comment] 2019-09-05 04:33
@jagadeeshRS, we encountered this situation when extracting one of our api's. We found the error in `ProductExtractor.cs` on the line 
>if (singleApiName == null || productAPIResources.SingleOrDefault(p => p.name.Contains(productName)) != null)

When fixing another error (#228), this issue was fixed as well. I've pull requested that fix into this repository (#229). If you want to, feel free to test my branch and see if that fixes your issue as well. Hopefully it will be merged pretty soon.

**Comment by jagadeeshRS** [comment] 2019-09-06 12:30
Thanks a lot @bremnes it is working  :)

**Comment by bremnes** [comment] 2019-09-09 15:06
@lucashuet93 , since you closed #228 take a look at this related issue as well. I think it can be closed, because of @jagadeeshRS's confirmation.

**Comment by bremnes** [comment] 2019-09-20 11:55
@jagadeeshRS Can you confirm that it's now working with the code provided in the Microsoft master branch (not mine)?

In that case, great if you can close the issue.

**Comment by bremnes** [comment] 2019-10-27 17:20
@jagadeeshRS, since you confirmed earlier that this fix works for you and it has been merged to master I'm closing this issue.

Feel free to re-open or comment if that's not the case.

**Closed by bremnes** 2019-10-27 17:20 UTC
