### ISSUE TITLE
Failing to Execute ARM templates

### ISSUE THREAD

**Issue by tagoreanand** [Azure/azure-api-management-devops-resource-kit#680] opened 2022-04-13 17:01 UTC
Hi Team,

I'm getting below error for most of the Spec files/APIs while deployment,

```
ERROR: {'code': 'InvalidTemplate', 'target': '/subscriptions/sh768-76f0-21o9-2j873k09l86e45/resourceGroups/rg-otfc-amn-sit-02/providers/Microsoft.Resources/deployments/paymentapplication-SubsequentAPITemplate', 'message': "Deployment template validation failed: 'The template resource 'otfc-amn-sit-02/paymentapplication/post-private/onlinefood/v8/accident/paymentapplication/policy' for type 'Microsoft.ApiManagement/service/apis/operations/policies' at line '60' and column '72' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-template/#resources for usage details.'.", 'additionalInfo': [{'type': 'TemplateViolation', 'info': {'lineNumber': 120, 'linePosition': 84, 'path': 'resources[2].type'}}]} 
```

Template structure and syntax - Azure Resource Manager
Describes the structure and properties of Azure Resource Manager templates (ARM templates) using declarative JSON syntax.

Please make it priority and help me to resolve this issue and FYI, I'm not seeing any failure template files under deployment(Resource Group)

Thank You.

**Comment by tagoreanand** [comment] 2022-04-13 17:18
1) v0.7 - https://github.com/Azure/azure-api-management-devops-resource-kit/releases/download/v0.7/reskit0.7.zip 
2) 
az deployment group create --resource-group $RGNAME --name "$APINAME" \
--template-uri "$ARTIFACTURI/$CONTAINERNAME/${{ parameters.apiName }}/${{ parameters.version }}/${{ parameters.apiName }}.${{ parameters.version }}-master.template.json$ARTIFACTSASTOKEN" \
--parameters \${{ parameters.apiName }}.${{ parameters.version }}-parameters.json    
3) Recommended config file only which includes below parameters
               apis, version, product, backend service url, Linked base URL(SAS token) to push ARM templates to Storage Account
4) No templates. Only Config file and Spec file
5) I didn't provide anything else

**Comment by adrianhall** [comment] 2022-04-13 17:27
Please attach the config file and spec file.

**Comment by tagoreanand** [comment] 2022-04-14 08:34
Hi, please find the requested spec files

[config&spec.zip](https://github.com/Azure/azure-api-management-devops-resource-kit/files/8487623/config.spec.zip)

**Comment by adrianhall** [comment] 2022-04-14 18:54
Thanks for that - bug added to backlog for investigation.

**Comment by tagoreanand** [comment] 2022-04-15 13:53
thank you and looking forward for your help at earliest

**Comment by tagoreanand** [comment] 2022-04-19 13:01
I don't know how the case got closed but i reopened 

Can I please get an update on this?

**Comment by adrianhall** [comment] 2022-04-19 14:44
There is no update on this.  I removed it from the backlog because you closed it.

**Comment by adrianhall** [comment] 2022-04-19 14:57
The information you provided was wrong.

When running the creator, I get the following error:

```
~\Downloads\config.spec> ..\reskit\ArmTemplates.exe create --configFile .\config.yml
[07:52:53 INF] Recognized create command...
Unhandled exception. YamlDotNet.Core.SemanticErrorException: (Line: 64, Col: 41, Idx: 2123) - (Line: 64, Col: 59, Idx: 2141): While parsing a block mapping, did not find expected key.
   at YamlDotNet.Core.Parser.ParseBlockMappingKey(Boolean isFirst)
   at YamlDotNet.Core.Parser.StateMachine()
   at YamlDotNet.Core.Parser.MoveNext()
   at YamlDotNet.Serialization.NodeDeserializers.DictionaryNodeDeserializer.DeserializeHelper(Type tKey, Type tValue, IParser parser, Func`3 nestedObjectDeserializer, IDictionary result)
```

This indicates that there is an error in your YAML file, which I can clearly see (VS Code actually highlights it as an error).  As such, we still do not have a reproduceable error. 

I'm removing this error from the backlog until we can reproduce the problem.

**Comment by tagoreanand** [comment] 2022-04-19 17:11
Hi Adrian - I have changed the actual data in Spec and config file before sending you.
Can you please share your email ids and availability to schedule a call for debugging session? Thank you and hope you understood

**Comment by adrianhall** [comment] 2022-04-19 21:25
If you have an Azure support contract, please feel free to open a support ticket and it will be routed to us.  If not, we can only provide support through issues.

Without a working reproduction, there is little we can do to help you.  The information you have provided thus far does not allow us to reproduce the problem.

**Comment by tagoreanand** [comment] 2022-04-20 14:25
I have raised the support request and waiting for the update

**Closed** 2022-05-18 16:29 UTC
Labels: bug, blocked, creator
