### ISSUE TITLE
[Extractor] splitAPIs generates incorrect base url params for APIs

### ISSUE THREAD

**Issue by romerve** [Azure/azure-api-management-devops-resource-kit#382] opened 2020-04-23 22:10 UTC
When using the extrator with `"splitAPIs": "true"` each API is placed into it's own folder. The parameters.json file created for each API reuses the extractor's config linkedTemplatesBaseUrl, and policyXMLBaseUrl without accounting for each API having their own folder resulting on incorrect URLs for policies, and linked template.

**To reproduce:**
Run the Extractor with:
`apimtemplate extract --extractorConfig ./config/apimExtract.json`

Ensure the config file has the following 3 properties:
```
    "linkedTemplatesBaseUrl": "https://raw.githubusercontent.com/............",
    "policyXMLBaseUrl": "https://raw.githubusercontent.com/............",
    "splitAPIs": "true",
```
**Generated parameters for API**
```json
    "LinkedTemplatesBaseUrl": {
      "value": "https://raw.githubusercontent.com/..../apim/contoso"
    },
    "PolicyXMLBaseUrl": {
      "value": "https://raw.githubusercontent.com/..../apim/contoso/policies"
    }
```
**URLs should be:**
Correct URLs should include the API name as follows
```json
    "LinkedTemplatesBaseUrl": {
      "value": "https://raw.githubusercontent.com/..../apim/contoso/**<API-NAME>**"
    },
    "PolicyXMLBaseUrl": {
      "value": "https://raw.githubusercontent.com/..../apim/contoso/**<API-NAME>**/policies"
    }
```
**Affects**:
- [v0.4-delta](https://github.com/Azure/azure-api-management-devops-resource-kit/releases/tag/v0.4) on Mac OS

**Workaround**:
- If using Github Actions or Azure Pipelines, override the parameters when deploying the API
- You can also manually update each *-parameters.json for each API

**Comment by adrianhall** [comment] 2022-04-20 20:39
I could not reproduce this on the latest code base, so closing as it is likely fixed.  If you are still experiencing an issue with the latest codebase, please open a new issue with all the required information.

Thank you.

**Closed by adrianhall** 2022-04-20 20:39 UTC
Labels: bug, extractor
