### ISSUE TITLE
Sibling dependencies out of sync for ApiTags and ProductAPIs templates

### ISSUE THREAD

**Issue by briiian** [Azure/azure-api-management-devops-resource-kit#600] opened 2021-12-15 03:23 UTC
Affects version V0.7

Steps to reproduce

- Create Api Tag
	- Display name: test
- Create Product
	- Display name: test
- Create API
	- Display Name: API1
	- API URL suffix: api1
	- Tags: test
	- Products: test
- Create API
	- Display Name: API2
	- API URL suffix: api2
	- Tags: 
	- Products: 
- Create API
	- Display Name: API3
	- API URL suffix: api3
	- Tags: test
	- Products: test
- Run the extractor:
`extract --sourceApimName YOUR_APIM_NAME --destinationApimName YOUR_APIM_NAME --resourceGroup YOUR_APIM_RESOURCE_GROUP --fileFolder TARGET_FOLDER_PATH`

Results (note the dependencies on **api2** tags that don't exist)

apiTags.template.json

> "resources": [
>     {
>       "properties": {
>         "displayName": "test"
>       },
>       "name": "[concat(parameters('ApimServiceName'), '/api1/test')]",
>       "type": "Microsoft.ApiManagement/service/apis/tags",
>       "apiVersion": "2021-01-01-preview",
>       "dependsOn": []
>     },
>     {
>       "properties": {
>         "displayName": "test"
>       },
>       "name": "[concat(parameters('ApimServiceName'), '/api3/test')]",
>       "type": "Microsoft.ApiManagement/service/apis/tags",
>       "apiVersion": "2021-01-01-preview",
>       "dependsOn": [
>         "[resourceId('Microsoft.ApiManagement/service/apis/tags', parameters('ApimServiceName'), '**api2**', 'test')]"
>       ]
>     }   
>     ]

productAPIs.template.json

> "resources": [
>     {
>       "name": "[concat(parameters('ApimServiceName'), '/test/api1')]",
>       "type": "Microsoft.ApiManagement/service/products/apis",
>       "apiVersion": "2021-01-01-preview",
>       "dependsOn": []
>     },
>     {
>       "name": "[concat(parameters('ApimServiceName'), '/test/api3')]",
>       "type": "Microsoft.ApiManagement/service/products/apis",
>       "apiVersion": "2021-01-01-preview",
>       "dependsOn": [
>         "[resourceId('Microsoft.ApiManagement/service/products/apis', parameters('ApimServiceName'), 'test', '**api2**')]"
>       ]
>     }
>     ]

**Comment by briiian** [comment] 2021-12-15 03:57
#601

**Comment by f-alizada** [comment] 2022-05-19 07:21
Hello @briiian.
Thank you for reporting the issue with detailed steps to reproduce. 
The issue is not reproducible, it was verified on the main branch and 1.0.0-beta.4 release. 
Due to this closing the bug.
Please feel free to reopen the issue if it's still reproducible on your side in latest releases.

**Closed by f-alizada** 2022-05-19 07:21 UTC
Labels: bug, extractor
