### ISSUE TITLE
Using multipleAPIs in the extractor settings extracts all Named Value Pairs

### ISSUE THREAD

**Issue by gaurav-p-sood** [Azure/azure-api-management-devops-resource-kit#494] opened 2021-05-14 12:36 UTC
Hi 

While using the setting multipleAPIs in the extractor settings.json , the extractor tool pulls all the a Named value pairs which shouldnt be the case and must extract only the Named value pairs specific to the API. 

I believe that is the also the case when one specific API is extracted. 

Please advice 

Regards
Gaurav

**Comment by adrianhall** [comment] 2022-04-20 19:58
Duplicate of #151

**Closed by adrianhall** 2022-04-20 19:58 UTC
Labels: bug, duplicate, extractor
