### ISSUE TITLE
[Extractor] Update extraction of named values for single api option (referenced by any entity)

### ISSUE THREAD

**Issue by lucashuet93** [Azure/azure-api-management-devops-resource-kit#151] opened 2019-04-10 16:42 UTC
Currently, the extractor extracts all named values for the single api option to ensure no deployment failure in case they are referenced

**Comment by DSpirit** [comment] 2020-11-30 19:40
@lucashuet93 I've implemented functionality to extract named values and backends for a single API. It's not very well tested, but for my case, it worked. It would be nice if you could have a look at my fork.

Currently, the named values inside a backend are not taken into respect, i.e. header and query values are not getting checked. If you think my approach makes sense in general, I could also check latter components for named values.

**Comment by DSpirit** [comment] 2020-12-02 07:55
Update: Now the backend is also being checked for named values. The main problem we have here is that the named values used in policies are using the _displayName_. Thus, I've added a REST request which queries the properties by displayName.
However, I had to use a regex for getting the properties and backend-ids (as well as properties used as a backend-id) which is not really a clean solution but I didn't manage to get the properties and backends in another way.

So as long as we can't retrieve all the backends and properties used in a policy / API by using a REST request, I don't know any other way to handle this.

**Comment by f-alizada** [comment] 2022-05-09 14:41
Hello everyone. 
It seems that this issue is duplicate of https://github.com/Azure/azure-api-management-devops-resource-kit/issues/549 and was already fixed. This is the PR which introduced filtering of the named-values https://github.com/Azure/azure-api-management-devops-resource-kit/pull/558.
Test configuration file:
```
{
    "sourceApimName": "source-apim",
    "destinationApimName": "dest-apim-instance",
    "resourceGroup": "rg",
    "splitAPIs": "false",
    "multipleAPIs": "echo-api",
    "fileFolder": "C:\\projects\\extractor\\results"
}
```
Extracted only referenced named-values. 
Please feel free to open a new issue if that is not fixed for you.
Thank you!

**Closed by f-alizada** 2022-05-09 14:41 UTC
Labels: feature, extractor
