### ISSUE TITLE
[BUG] [Extractor] GetApiVersionSets does not support paged response.

### ISSUE THREAD

**Issue by Phetparisouk** [Azure/azure-api-management-devops-resource-kit#442] opened 2020-10-22 15:12 UTC
Hello, I got some issue with the extractor tool. 

Every time I add an API to the APIM, I always check the "version this API" button, even when the API only has one version. 

So when I used the tools to extract my APIs from the APIM, it should also extract/generate their apiVersionSets.template.json file. 
But for some apis, it does not.

I am aware about the --apiVersionSetName parameter which can extract the versionset, but I mostly use the extractor tools with the "apiName" params to extract my api. So I cannot use both arguments at the same time.
  
Here is my extractparams.json configuration : 
{
"sourceApimName": "my_apim_source",
"destinationApimName": "my_destination_apim",
"resourceGroup": "api_resource_group",
"apiName": "target_api_name",
"fileFolder": "output_path_for_my_extracted_api",
"policyXMLBaseURL" : "url_policy"
}

Best regards,

**Comment by RupengLiu** [comment] 2020-12-10 06:59
Triaged

**Comment by RupengLiu** [comment] 2021-03-25 18:19
@Phetparisouk to more clearly understand your issue, if you specify "apiName", then it should only extract API templates, not versionset, since "apiName" is the identifier of this API not the versionset, if I enabled extracting versionset by using "apiName", then it might cause some issues (like if a customer provide the apiName, and this api has versionset, then it will extract the versionset, not the api), but I would like to know more about your use case so we can figure out a goo approach

**Comment by tasb** [comment] 2021-06-01 18:47
I found the issue regarding this.
On "GetAPIVersionSetsAsync" method you are getting only 100 results. If your source APIM have a lot of versionSets you cannot get the related with the API trying to extract.

Need to add a $top parameter on the query or do this dynamic since you receive a "nextLink" URL from the reply

**Comment by f-alizada** [comment] 2022-06-29 10:08
Hello @Phetparisouk.
Currently resources from API are fetched using the pagination if exists, the same goes for the ApiVersionSets. 
Also, I have checked and verified the behaviour of the extractor using the configuration provided in the issue description:
```
{
"sourceApimName": "my_apim_source",
"destinationApimName": "my_destination_apim",
"resourceGroup": "api_resource_group",
"apiName": "target_api_name",
"fileFolder": "output_path_for_my_extracted_api",
"policyXMLBaseURL" : "url_policy"
}
```
The version set was also extracted. 
Closing the issue taking into account it is not reproducible anymore. 
Please feel free to reopen the bug or create a new one if the behaviour didn't change and you are facing the same problem on main branch or latest releases. 
Best regards.

**Closed by f-alizada** 2022-06-29 10:08 UTC
Labels: bug, extractor
