### ISSUE TITLE
Creator tool generating parameters file which is not correct for the Version Set Template

### ISSUE THREAD

**Issue by shakhand208** [Azure/azure-api-management-devops-resource-kit#805] opened 2022-08-29 09:32 UTC
### Discussed in https://github.com/Azure/azure-api-management-devops-resource-kit/discussions/804

<div type='discussions-op-text'>

<sup>Originally posted by **shakhand208** August 29, 2022</sup>
Hi Folks,

We have been working on a scenario where the configuration of our creator config creates 3 templates and 1 parameter file
- Initial API Template
- Subsequent API Template
- APIVersionSets Template
- Parameter File

The Initial API and Subsequent API Templates uses 2 Parameters - APIm Service Name and API Service URL which are available in the parameter file so these ARM Temp;ates gets deployed in Azure APIM successfully.
However in the APIVersionSets Templates, there is only 1 parameter in use i.e.; APIM Service Name. Hence when the parameter file created by the kit is used to deploy APIVersion Sets, we are getting below Error
**Deployment template validation failed: 'The template parameters 'api-ServiceUrl' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters for this template are 'apimServiceName'.**

Is there any solution to generate template specific parameter files to avoid such errors?</div>

**Comment by tomkerkhove** [comment] 2022-08-29 14:32
Duplicate of https://github.com/Azure/azure-api-management-devops-resource-kit/discussions/804

**Closed by tomkerkhove** 2022-08-29 14:32 UTC
