### ISSUE TITLE
[extractor] parameterizing loggerid / appinsights breaks deployment

### ISSUE THREAD

**Issue by mplasch** [Azure/azure-api-management-devops-resource-kit#548] opened 2021-07-22 21:48 UTC
When attempting to parameterize the appinsights logger I receive this error:
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"InvalidTemplate","message":"Unable to process template language expressions for resource '/subscriptions/xxxxxxxxx/resourceGroups/myresourcegroup/providers/Microsoft.ApiManagement/service/apim-instance/apis/swagger-petstore/diagnostics/applicationinsights' at line '291' and column '5'. 'The language expression property 'swaggerpetstore' doesn't exist, available properties are 'applicationinsights'.'"}]}.

I opened a case with MS to see if I was incorrectly passing the object sub properties and they told me to remove the api name from it and it did work.  Seems that passing the api name (swaggerpetstore) in the sub property is breaking it.

Issue:
ARM template deployment failure
Cause:
Code issue line 293 - logger pointing to app insights with new logger, should just be app insights. 
Resolution:
strike through should be removed. line 293  "loggerId": "[parameters('ApiLoggerId').swaggerpetstore.applicationinsights]",

**Comment by f-alizada** [comment] 2022-05-26 08:36
Hello @mplasch.
Thank you for raising issue.
Currently the bug is not reproducible.

Extractor config used:

```
{
    "sourceApimName": "api-management-1",
    "destinationApimName": "api-management-2",
    "resourceGroup": "resource-group-name",
    "fileFolder": "path\to\folder",
    "paramApiLoggerId": "true"
}
```

Generated template for parameters:

```
...
"apiLoggerId": {
      "value": {
        "apiname": {
            "applicationinsights": "value"
        }
    }
}
...
```

Generated apis template:
```
...
    {
      "apiVersion": "2021-08-01",
      "type": "Microsoft.ApiManagement/service/apis/diagnostics",
      "name": "[concat(parameters('apimServiceName'), '/apiname/applicationinsights')]",
      "properties": {
        "alwaysLog": "allErrors",
        "loggerId": "[parameters('apiLoggerId').apiname.applicationinsights]",
        "httpCorrelationProtocol": "None",
        "verbosity": "information",
        "logClientIp": false,
      }
    }
...
```

Deployment of the templates were successful without errors. 
It was tested on the main branch.


Since the bug is not reproducible, closing the issue.

Please feel free to reopen the bug if the behaviour didn't change and you facing the same issue on main branch or latest releases.

Thank you :)

**Closed by f-alizada** 2022-05-26 08:36 UTC
Labels: bug, extractor
