### ISSUE TITLE
API Extraction fails with 404 Not Found

### ISSUE THREAD

**Issue by nirupamasrivastava** [Azure/azure-api-management-devops-resource-kit#564] opened 2021-08-17 18:35 UTC
Hello,

I downloaded latest released version of **azure-api-management-devops-resource-kit** from master and used Extractor Tool to extract ARM Templates for APIM APIs. The Extraction process fails with below error message : 

Error occured: Response status code does not indicate success: 404 (Not Found).
Response status code does not indicate success: 404 (Not Found).

Thanks and Regards

**Comment by preetiben** [comment] 2021-08-24 23:46
Facing the same issue. Any direction on what's causing this issue or any temporary workarounds would be very helpful. Thanks!

**Comment by RupengLiu** [comment] 2021-09-13 04:53
can you share the log where this error throws?

**Comment by SParekh** [comment] 2022-01-12 21:58
Assuming you have verified following:
a. az login
b. az account set --subscription <subscription_id>
c. Verifying that your resource group is in list "az group list".
d. Name specified for your source APIM is correct.

One issue could be the cloud your resource exists in.
In EntityExtractor.cs, the baseUrl is hard coded to Azure.
![image](https://user-images.githubusercontent.com/1882391/149226437-6e5b7653-6e00-4edc-8c07-71865f918e31.png)

so if your source APIM resources are in Azure Government it will throw you 404. Change the "baseUrl" to the management url for respective cloud and it should resolve 404.

**Comment by adrianhall** [comment] 2022-02-04 17:04
We currently do not have enough information to diagnose this.  If you receive a 404 (or any other error), please ensure you share the log from the extractor.  That will allow us to diagnose the problem.  If you cannot provide the log publically, then please work through Azure support to open a ticket and provide the log privately.

Closing since we cannot reproduce and no further information has been provided.

**Closed by adrianhall** 2022-02-04 17:04 UTC
Labels: bug

**Comment by DeagleGross** [comment] 2022-03-22 14:53
Currently there is no descriptive comment for the issue. Please, provide more description (logs) by again launching the extraction. Also make sure to pull the latest repo commits to `main`, because code was refactored.

Moving this issue to `to be released` state, because there is nothing I can do right now.
If there are any troubles, feel free to open a new issue
