### ISSUE TITLE
[Creator] Parameterized serviceUrl is with Type Object

### ISSUE THREAD

**Issue by devgodman** [Azure/azure-api-management-devops-resource-kit#485] opened 2021-04-26 01:59 UTC
In APITemplateCreator,  
if (String.IsNullOrEmpty(api.serviceUrl))
{
   apiTemplate.parameters.Add(ParameterNames.ServiceUrl, new TemplateParameterProperties() { type = "object" });
}
It shows that service URL can be parametized for different environments. However, the type is set object instead of string. 
What value should be passed?

**Comment by devgodman** [comment] 2021-04-28 07:12
I change the type to "string" and the creator works fine.

**Comment by levimatheri** [comment] 2021-05-08 17:26
Yeah, why is the `serviceUrl` an object instead of a string?

**Comment by majorvin** [comment] 2021-06-14 20:07
Im not sure if this feature covered making serviceURL as parameters. e.g. (when using demo) initial and subsequent .json files hardcoding the serviceUrls but it can/should retrieve it from parameters('serviceUrl')

**Comment by adrianhall** [comment] 2022-04-20 20:00
Duplicate of #577

**Closed by adrianhall** 2022-04-20 20:00 UTC
Labels: duplicate, feature, creator
