### ISSUE TITLE
Extracted ARM template from Extractor - Invalid template error

### ISSUE THREAD

**Issue by nagashreeb** [Azure/azure-api-management-devops-resource-kit#737] opened 2022-06-02 15:48 UTC
## Where did you encounter this bug?

* [] Extractor

## Describe the bug

The API ARM template extracted from extractor tool is not getting deployed, encountering the following error
2022-06-01T18:44:27.9840926Z ERROR: {'code': 'InvalidTemplate', 'message': 'Deployment template validation failed: 'The template resource 'apim-common-qa2-01/cuid-api-v3/post-api-token-provider' at line '910' and column '5' is not valid: The language expression '\r\n {\r\n "id": "string",\r\n "type": "string",\r\n "data": {}\r\n }\r\n' is not valid: the string character '{' at position '4' is not expected.. Please see https://aka.ms/arm-template-expressions for usage details.'.', 'additionalInfo': [{'type': 'TemplateViolation', 'info': {'lineNumber': 910, 'linePosition': 5, 'path': 'properties.template.resources[7]'}}]}
2022-06-01T18:45:02.2262356Z ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"NotFound","message":"{\r\n "error": {\r\n "code": "ResourceNotFound",\r\n "message": "Api not found.",\r\n "details": null\r\n }\r\n}"}]}}

[base-cuid-api-v3-api.template.txt](https://github.com/Azure/azure-api-management-devops-resource-kit/files/8819061/base-cuid-api-v3-api.template.txt)

Attaching the API template for which the error was encountered.

Any help on this is appreciated.

Extracting as:
C:\work\xxxxxx\APIM\azure-api-management-devops-resource-kit-master\src\APIM_ARMTemplate\apimtemplate> dotnet run extract --extractorConfig .\extractorparams_apisWithSeparateFolders.json

## What version of the DevOps Resource Kit is being used?

Yes bug is reproducible on the latest released version and the latest beta source available in github

## What version of dotnet are you running?

.Net version: 6.0.300

## What platform (OS and version) are you running on?

Windows, running from visual studio code 1.57.1

## The command line you are running?
C:\work\xxxxxx\APIM\azure-api-management-devops-resource-kit-master\src\APIM_ARMTemplate\apimtemplate> dotnet run extract --extractorConfig .\extractorparams_apisWithSeparateFolders.json

## The configuration file being used?

C:\work\xxxxxx\Azure API Management\azure-api-management-devops-resource-kit-master\src\APIM_ARMTemplate\apimtemplate\extractorparams_apisWithSeparateFolders.json
## How is your API Management Instance set up?

* What SKU is being used (as the source for extractor or destination for creator)? Tier: Developer (No SLA); source APIM instance for the extractor: apim-common-dev-01
* Do you have full admin rights to the service? Yes
* Is the service in a VNET?  If so, describe how it is configured? 
Not sure, the portal shows Virtual Network as internal and the following virtual IP 
Virtual IP (VIP) addresses:
[public: 20.236.9.124, private: 10.204.28.7](https://docs.microsoft.com/azure/api-management/api-management-howto-ip-addresses?WT.mc_id=Portal-Microsoft_Azure_ApiManagement#ip-addresses-of-api-management-service-in-vnet)

## What logs (if any) were produced?

* Feel free to provide a link to a gist if needed.

## Expected behavior

The extracted ARM template should be successfully deployed to APIM. 

## Additional context

the ARM template is attached here:
[base-cuid-api-v3-api.template.txt](https://github.com/Azure/azure-api-management-devops-resource-kit/files/8846783/base-cuid-api-v3-api.template.txt)

Extractor config file is attached here
[extractorparams_apisWithSeparateFolders.txt](https://github.com/Azure/azure-api-management-devops-resource-kit/files/8825449/extractorparams_apisWithSeparateFolders.txt)

**Comment by nagashreeb** [comment] 2022-06-06 17:47
APIM seems to have an issue with a sample response (in the extracted ARM template, this was loaded by creating the API in APIM using the open API spec)
"sample": "[\r\n {\r\n \"id\": \"string\",\r\n \"type\": \"string\",\r\n \"data\": {}\r\n }\r\n]",

if I remove this line the template validation is successful.
My deduction is that, ARM expressions begin with [, example "name": "[concat(parameters('ApimServiceName'), '/cuid-api-v3/post-api-token-refresh')]" and this sample is being evaluated as an expression.
I tried with escaping the [ braces as below,
"sample": "[[\r\n {\r\n \"id\": \"string\",\r\n \"type\": \"string\",\r\n \"data\": {}\r\n }\r\n]]",
and the template was validated successfully.

The extractor should have added the escape sequence for the sample json response array while extracting the ARM template for the API.

**Comment by f-alizada** [comment] 2022-06-07 07:47
Hello @nagashreeb thank you for raising the issue.
The **Sample** property extracted in the arm templates was removed in this PR #710 and merged into main branch and available in the release [1.0.0-beta.5](https://github.com/Azure/azure-api-management-devops-resource-kit/releases/tag/1.0.0-beta.5).
Could you please share what versions of DevOps Resource Kit was used?
Thank you

**Comment by nagashreeb** [comment] 2022-06-07 17:05
@f-alizada , can you let me know how to find the version of the devops resource kit? I can only see that I downloaded the latest version that was available on 5/11/2022 - azure-api-management-devops-resource-kit-master.zip

**Comment by f-alizada** [comment] 2022-06-08 07:19
Hello @nagashreeb.
The codebase at the mentioned date didn't have the PR merged #710. 
PR was merged on 2022-05-17. 
There are two options to acquire this update: 

1. Get the latest release from https://github.com/Azure/azure-api-management-devops-resource-kit/releases. [1.0.0-beta.5](https://github.com/Azure/azure-api-management-devops-resource-kit/releases/tag/1.0.0-beta.5)
2. Get the latest updates from main branch

Please let me know if the issue is still reproducible on main branch or 1.0.0-beta.5 release.

**Comment by nagashreeb** [comment] 2022-06-09 18:16
Hi @f-alizada , I used the latest beta release and extracted. I see that the "sample" attribute is no longer there in the ARM template.
I have two follow on questions:
1. the ARM templates generated from the latest resource kit is changed - more templates are generated than the earlier version. It would be good to know information about each template. can you pls help with that. I do see two of them which are new logger template and groups template
2. Since the sample is now removed from the ARM template, how does it show up in the devportal documentation for the API? will that be visible or not?

**Comment by f-alizada** [comment] 2022-06-09 19:11
Hello @nagashreeb.
Answering your questions: 

1. [Groups template](https://docs.microsoft.com/en-us/azure/templates/microsoft.apimanagement/service/groups?tabs=json)  refers to [Groups](https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-create-groups) of API management, [Loggers template](https://docs.microsoft.com/en-us/azure/templates/microsoft.apimanagement/service/loggers?tabs=json) for monitoring. 
2. **Sample** property was replaced with **Examples** (PR #706) to align with currently used API version. Examples has information about the sample data, hence will be deployed as well. 

If you have any questions regarding this topic please let me know

**Comment by adrianhall** [comment] 2022-06-09 19:39
Closing issue, since there is no additional work to be done.

**Closed by adrianhall** 2022-06-09 19:39 UTC
Labels: bug, blocked, extractor
