### ISSUE TITLE
"paramServiceUrl":"true" adds serviceUrl to productAPIs.template.json but never passes it

### ISSUE THREAD

**Issue by waelkdouh** [Azure/azure-api-management-devops-resource-kit#505] opened 2021-05-28 21:48 UTC
"paramServiceUrl":"true" adds serviceUrl to productAPIs.template.json but never passes it from the master template which causes the template validation to fail during deployment. This seems like a bug.

**Comment by nahojs** [comment] 2021-06-10 00:13
I have similar issue. ServiceUrl is not created in the Api-parameter file. I manually commented out that creation-part and now it works as expected.

**Comment by esimkowitz** [comment] 2021-07-02 01:10
I have the same issue with the new release

**Comment by adrianhall** [comment] 2022-04-20 19:56
Dupe of #577 so closing this one.

**Closed by adrianhall** 2022-04-20 19:56 UTC
Labels: bug, creator
