### ISSUE TITLE
splitAPIs option from Extractor utility did not output files in separate folders

### ISSUE THREAD

**Issue by aditiketkar** [Azure/azure-api-management-devops-resource-kit#668] opened 2022-04-01 15:27 UTC
![image](https://user-images.githubusercontent.com/27771726/161294402-623cdbc7-a3f5-4804-8ac8-bdce0ea04ef0.png)

**Comment by shuqiz423** [comment] 2022-04-04 10:50
Hi, may I know how you reached this step? I cannot run the extractor with the extractor argument:
https://github.com/Azure/azure-api-management-devops-resource-kit/tree/main/src#extractor-arguments

Any advise would be much appriciated!

**Comment by adrianhall** [comment] 2022-04-06 16:04
@shuqiz423 please open a new issue with your queston as it is not related to this issue.

**Comment by DeagleGross** [comment] 2022-04-20 15:33
Hello @aditiketkar,
Thanks for submitting an issue.

I tried to launch extractor-config with `splitAPIs` parameter
![image](https://user-images.githubusercontent.com/31598696/164267312-f291b3f5-2de2-403b-bcbf-9a3f19fc6d71.png)

And (sorry for my painting skills) I got every single api deployed in different folder. As you can see, there is a separate folder to `revisioned` api & for `versioned` api.
![image](https://user-images.githubusercontent.com/31598696/164267095-53365562-ede8-4075-aca4-75a5b9725a3b.png)

So from your screen I see that you made a screenshot of general files. It is normal, I would assume. Because there is no reason to copy every single template.

Probably I can not understand your use-case. Can you please share your thoughts? I will close this issue for now, because it seems to be by design.

**Closed by DeagleGross** 2022-04-20 15:33 UTC
Labels: bug, extractor
